### GET - pobranie danych meta wybranego zdjęcia
GET http://localhost:3000/api/filters/metadata/8fa6bd38-5a73-4bff-9dd3-1f746c2b4013 HTTP/1.1



### PATCH /api/filters
PATCH  http://localhost:3000/api/filters HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU
content-type: application/json

{   
  "id":"b3eaeb82-a0a6-4316-b95d-a0badded57cd",
  "filter":"rotate",
  "size": {"w": 100, "h": 100, "l": 100, "t": 100},
  "color": {"r": 0 ,"g": 0, "b": 255},
  "format": "jpg",
  "angle": 90  
}