### GET - pobranie danych meta wybranego zdjęcia
GET http://localhost:3000/api/filters/metadata/8fa6bd38-5a73-4bff-9dd3-1f746c2b4013 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWUzQGVtYWlsLnBsIiwidGltZSI6MTcxNTQyOTUzODUyNiwiaWF0IjoxNzE1NDI5NTM4LCJleHAiOjE3MTU1MTU5Mzh9.9pIdbuL1UVQk1ubf3dy30-DSluT0Ldlef5pOQsf6xCg



### PATCH /api/filters
PATCH  http://localhost:3000/api/filters HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGluc3RhLnBsIiwidGltZSI6MTcxNzg0MTgwNzUzNywiaWF0IjoxNzE3ODQxODA3LCJleHAiOjE3MTc5MjgyMDd9.wjC0vUoCaND5RSiy2ENpaJXc_5O2uT9l3k52UV2IF5c
content-type: application/json

{   
  "id":"8c7d2a9d-0ff3-4f12-ba74-a2879b92528b",
  "filter":"negate",
  "size": {"w": 100, "h": 100, "l": 100, "t": 100},
  "color": {"r": 0 ,"g": 0, "b": 255},
  "format": "avif",
  "angle": 95
}