### GET - autoryzacja konta 
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTJlQGVtYWlsLnBsIiwiaWF0IjoxNzE0NDEzNTMwLCJleHAiOjE3MTQ0MTM1NjB9.ulU3_Ur-wkulMtc9qXabH8zRLFeC_B40_h1TIdAlgzA HTTP/1.1


### GET - pobranie listy użytkowników
GET http://localhost:3000/api/user/ HTTP/1.1


### GET - wylogowanie
GET http://localhost:3000/api/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAc3p3YXJja2FtLmN0OC5wbCIsInRpbWUiOjE3MTY3MzMwMDg5NTYsImlhdCI6MTcxNjczMzAwOCwiZXhwIjoxNzE2ODE5NDA4fQ.uH9tYonlob44QmEZBUFQ3aFTF88LS0qMCQX3dw5T7mU

###GET - pobranie danych profilu
GET http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAc3p3YXJja2FtLmN0OC5wbCIsInRpbWUiOjE3MTY3MzMwMDg5NTYsImlhdCI6MTcxNjczMzAwOCwiZXhwIjoxNzE2ODE5NDA4fQ.uH9tYonlob44QmEZBUFQ3aFTF88LS0qMCQX3dw5T7mU
### POST - rejestracja użytkownika
POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name",
   "lastName": "lastName",
   "email":"user@szwarckam.ct8.pl",
   "password":"zaq1@WSX"
}
### POST - logowanie użytkownika
POST http://localhost:3000/api/user/login HTTP/1.1
//Authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

{
  "email":"user@szwarckam.ct8.pl",
  "password":"zaq1@WSX"
}
### POST - zmiana hasła użytkownika
POST http://localhost:3000/api/user/changepass HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAc3p3YXJja2FtLmN0OC5wbCIsInRpbWUiOjE3MTY3MzMwMDg5NTYsImlhdCI6MTcxNjczMzAwOCwiZXhwIjoxNzE2ODE5NDA4fQ.uH9tYonlob44QmEZBUFQ3aFTF88LS0qMCQX3dw5T7mU

{
  
  "oldPassword":"zaq1@WSX",
  "newPassword":"zaq2!WSX"
}

### POST - resetowanie hasła użytkownika
POST http://localhost:3000/api/user/resetpass HTTP/1.1
//Authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

{
  "email":"user@szwarckam.ct8.pl"
}


###PATCH - aktualizuje profil użytkownika
PATCH http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAc3p3YXJja2FtLmN0OC5wbCIsInRpbWUiOjE3MTY3MzMwMDg5NTYsImlhdCI6MTcxNjczMzAwOCwiZXhwIjoxNzE2ODE5NDA4fQ.uH9tYonlob44QmEZBUFQ3aFTF88LS0qMCQX3dw5T7mU

{
 "name": "Kamil",
 "lastName": "Szwarc",
 "bio": "Autor"
}

###POST - Wysłąnie zdjęcia profilowego
POST http://localhost:3000/api/profile HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAc3p3YXJja2FtLmN0OC5wbCIsInRpbWUiOjE3MTY3MzMzODUwOTUsImlhdCI6MTcxNjczMzM4NSwiZXhwIjoxNzE2ODE5Nzg1fQ.c8IvqNag10WO1Y_9Gf7eslzF83FpaIZ3Wghd2YAs4vw
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input1222.png"
Content-Type: image/png

< ./logo2.png

------FormBoundary1234

